### PR TITLE
Fix missing theme data in setup.py

### PR DESCRIPTION
**Pull request by petercolberg**
This commit includes README.md in the tarball generated with `python3 setup.py sdist`.

Further this fixes an error when generating a Debian source package:
```
sudo apt-get install python3-all-dev python3-stdeb
python3 setup.py --command-packages=stdeb.command sdist_dsc
```

### CODE REVIEW

**Comment by petercolberg** [comment]
The theme data is now installed as well.

**Comment by petercolberg** [comment]
@ViralBShah, @pao, and @garrison, could you review and merge this pull request, and tag an initial JuliaDoc version 0.1.0? This would make it much easier to package JuliaDoc for Debian, which is a prerequisite for getting Julia 0.4.0 into Debian.

**Comment by petercolberg** [comment]
@stevengj, in case you are co-maintaining JuliaDoc, could you take a look at pull request #17?

**Comment by pao** [comment]
What is your interest in independently packaging this? Build the docs, then forget it exists. It's basically on life support anyways--I think my crummy packages were the only ones that even used it outside the core, and core documentation will be moving away from Sphinx soon.

**Comment by petercolberg** [comment]
JuliaDoc is an external dependency for building Julia 0.4, and as a Python package it should be packaged separately for Debian.

**Comment by pao** [comment]
That's a very rules-lawyery interpretation of "external dependency." It's separated so we can use it more easily with ReadTheDocs, that's all. It's not needed at all to use Julia or read its documentation, and can only make the installation more confusing.

**Comment by petercolberg** [comment]
Debian differentiates between build dependencies and installation dependencies. The package would not be needed for installation of julia, but for compilation by the maintainer or build daemon. Since you mention that JuliaDoc will be deprecated soon, however, it seems better to embed it in the julia source.

**Comment by petercolberg** [comment]
Nevertheless, please review and merge the commits that fix `setup.py`.

**Comment by pao** [comment]
It's not clear to me what is being fixed, seeing as it currently works in both Julia's build system and on RTD. I'm more concerned about those things not suddenly breaking. Someone who understands what is being done here and is more sure of not screwing things up should take a look.

**Pull request closed without merging**
